To start developing the application, you’ll need to set up the
development environment.

== Run & Build using npm

NeoDash is built with React. You’ll need `npm` installed to run the web
app.

____
Use a recent version of `npm` and `node` to build NeoDash. The
application has been tested with npm 8.6 & node v17.4.0.
____

To run the application in development mode: - clone this repository. -
open a terminal and navigate to the directory you just cloned. - execute
`npm install` to install the necessary dependencies. - execute
`npm run dev` to run the app in development mode. - the application
should be available at http://localhost:3000.

To build the app for production: - follow the steps above to clone the
repository and install dependencies. - execute `npm run build`. This
will create a `build` folder in your project directory. - deploy the
contents of the build folder to a web server. You should then be able to
run the web app.

== Run locally with Docker

Pull the latest image from Docker Hub to run the application locally:

....
# Run the application on http://localhost:5005
docker pull nielsdejong/neodash:latest
docker run -it --rm -p 5005:5005 nielsdejong/neodash
....

____
Windows users may need to prefix the `docker run` command with `winpty`.
____

== Build Docker image

A pre-built Docker image is available
https://hub.docker.com/r/nielsdejong/neodash[on DockerHub]. This image
is built using the default configuration (running in editor mode,
without SSO).

=== To build the image yourself:

Make sure you have a recent version of `docker` installed to build the
multi-stage NeoDash image and run it.

On Unix (Mac/Linux) systems:

....
docker build . -t neodash
....

If you use Windows, you might need to prefix the command with `winpty`:

....
winpty docker build . -t neodash
....

After building, you can run the image with: ``` docker run -it –rm -p
5005:5005 neodash
